version: '3'

services:
  app_gin_gonic:
    build:
      context: .
      dockerfile: deploy/main/Dockerfile
    restart: on-failure
    depends_on:
      - db_gin_gonic
      - redis_gin_gonic
    environment:
      - DB_SCHEMA=public
      - DB_USERNAME=fan
      - DB_PASSWORD=lupa_password
      - DB_NAME=gin_go
      - DB_HOST=db_gin_gonic
      - DB_PORT=5432
      - DB_TIMEZONE=Asia/Jakarta
      - DB_MAX_CON_IDLE=10
      - DB_MAX_CON_OPEN=10
      - DEBUG=false
      - APP_TIMEOUT=10
      - APP_PORT=:3001
      - PROXY_URL=127.0.0.1;::1
      - JWT_SECRET_KEY=whosyourdaddy
      - JWT_DURATION=1h
      - REDIS_HOST=redis_gin_gonic
      - REDIS_PORT=6379
      - REDIS_DB=
      - REDIS_PASSWORD=esW=]VFgYJM39:pu
      - REDIS_TIMEOUT=10s
      - MAX_REQUEST=10
      - EXPIRED_REQUEST=10s
      - MIGRATION_DIR=../../migrations/pgsql
      - NEED_SEEDER=true
    ports:
      - "8080:3001"
    networks:
      - gin_gonic_network
  db_gin_gonic:
    restart: on-failure
    image: postgres:latest
    container_name: pgsql_gin_gonic
    environment:
      POSTGRES_USER: fan
      POSTGRES_PASSWORD: lupa_password
      POSTGRES_DB: gin_go
    volumes:
      - ./deploy/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - gin_gonic_network
  redis_gin_gonic:
    restart: on-failure
    image: 'bitnami/redis:7.0.5-debian-11-r3'
    container_name: redis_gin_gonic
    hostname: redis
    ports:
      - '6378:6379'
    volumes:
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./deploy/redis/apps/logs:/apps/logs
      - ./deploy/redis/data:/data
    command: /bin/sh -c "redis-server --requirepass esW=]VFgYJM39:pu"
    networks:
      - gin_gonic_network
networks:
  gin_gonic_network:
    driver: bridge